### ISSUE TITLE
Bug: 502 Bad Gateway after upgrade to php 7.4 (Manjaro)

### ISSUE THREAD

**Issue by FarizInk** [cpriego/valet-linux#260]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Manjaro 18.1.4          | 7.4.1       | 2.2.8         |

- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `2.2.8`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
valet.sock permission denied

![image](https://user-images.githubusercontent.com/20873955/71141358-6e314800-2246-11ea-9518-e064b728a03e.png)

**Comment by jmarcher** [comment]
Should be fixed on v2.2.9

**Comment by markovic-nikola** [comment]
Hello,
This issue is still happening to me, on every boot I need to initiate a `valet install` command in order to get php-fpm up.

Distro (Name and version) | PHP Version | Valet version
--- | --- | ---
Manjaro **18.1.5** | Valet **2.2.10** | PHP **7.4.2**

![image](https://user-images.githubusercontent.com/16388545/74652186-c1137700-5185-11ea-99f7-53d264fbfe57.png)

Any ideas how to resolve this?
Thanks.

**Comment by jmarcher** [comment]
@markovic-nikola Can you open a new issue with your problem and the output of `journalctl -xb -u php-fpm`
