### ISSUE TITLE
Add support for Solus

### ISSUE THREAD

**Issue by AkgunFatih** [cpriego/valet-linux#265]
in [Solus](https://getsol.us) all you do is
`sudo eopkg it php -y` then it installs [php 7.3.13](https://dev.getsol.us/source/php/browse/master/package.yml) which includes fpm already

![Screenshot from 2020-01-30 14-10-53](https://user-images.githubusercontent.com/39423167/73452529-5d5a1300-436a-11ea-8344-71be021b084c.png)

**Comment by AkgunFatih** [comment]
@jmarcher whats the reason ?

**Comment by jmarcher** [comment]
There is no question nor problem presented.

**Comment by AkgunFatih** [comment]
@jmarcher Sorry. After installing valet i get this error

![image](https://user-images.githubusercontent.com/39423167/73823528-befdff80-47f8-11ea-97ff-7e4a55b6f03b.png)

**Comment by jmarcher** [comment]
I'm not familiar with Solus or eopkg, can you tell me how do you get the list of installed packages from eopkg?

At the moment the PackageManager driver is trying to use `dpkg -l {$package} | grep '^ii' | sed 's/\s\+/ /g' | cut -d' ' -f2` which i'm sure is wrong (or does eopkg depend on dpkg?)

**Comment by AkgunFatih** [comment]
dpkg is for debian eopkg is like apt-get but for solus
to list installed apps you run `eopkg la`

i tried this command `eopkg li nginx | grep '^ii' | sed 's/\s\+/ /g' | cut -d' ' -f2`
but it returns empty

**Comment by jmarcher** [comment]
Can you just paste an output of `eopk li` in plaintext?

Just as a test, can you see what comes as output from: `eopkg li | cut -d ' ' -f 1 | tr '\n' ' '`

**Comment by AkgunFatih** [comment]
srry for late response...
this is the output of `eopkg li | cut -d ' ' -f 1 | tr '\n' ' '`

![image](https://user-images.githubusercontent.com/39423167/73867134-6f462500-4846-11ea-9383-acba08484c76.png)

**Comment by jmarcher** [comment]
Should be fixed on v2.2.12

**Comment by AkgunFatih** [comment]
still the same problem :(

![image](https://user-images.githubusercontent.com/39423167/73876200-e2f02e00-4856-11ea-8608-cf45aab7ce9a.png)

**Comment by jmarcher** [comment]
That's weird, can you please post an output of `eopk li` in **plaintext** not a screenshot.

**Comment by jmarcher** [comment]
If this is the case, a few changes need to be made to the PackageManager contract, will see if I find the time to do so. Please if you have some time feel free to open a PR supporting this.

**Comment by AkgunFatih** [comment]
i removed the part where it checks for php-fpm package but then it keeps getting more issues with dnsmasq.. i gave up as i am not expert in coding

**Comment by jmarcher** [comment]
Ok, I can not help you if you do not provide me what I ask you for, I'm not willing to install Solus on my computer nor a VM in order to fix this issue.
