### ISSUE TITLE
Bug: Lost network connection after running valet install

### ISSUE THREAD

**Issue by datlechin** [cpriego/valet-linux#368]
**Basic info**

| Distro (Name and version) | PHP Version | Valet version |
| ------------------------- | ----------- | ------------- |
| Ex: Ubuntu 22.04          | 8.1.2    | Latest         |

- [x]I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-linux (`valet --version`): `2.2.32`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After running `valet install` for a few seconds, the network connection is lost (the network icon shows an exclamation mark)

**What was supposed to happen?**
Lost Internet connection

**What actually happened?**
Network icon with exclamation mark and cannot network access

**How to reproduce this?**
- Install new Ubuntu 22.04
- Install Composer, Install Valet
- Run `valet install` and lost internet.

I have reinstalled Ubuntu and tried to install Valet 3 times but still get the same problem

**What is the solution?**
N/A

**Comment by EmilioBravo** [comment]
I have the same problem after upgrading to Ubuntu 22.04. Lost connection. And valet-linux doesn't serve my sites either. I had to uninstall valet-linux to get internet connection back.

**Comment by datlechin** [comment]
> I have the same problem after upgrading to Ubuntu 22.04. Lost connection. And valet-linux doesn't serve my sites either. I had to uninstall valet-linux to get internet connection back.

even though i removed valet linux from ubuntu 22.04 but the network connection still not working, so i have to reinstall ubuntu

**Comment by EmilioBravo** [comment]
@datlechin you have to follow all the instructions in the docs https://cpriego.github.io/valet-linux/#uninstalling

Specially this: 

* Make sure systemd-resolved is running (systemctl status systemd-resolved), if not, enable (systemctl enable systemd-resolved) and start it (systemctl start systemd-resolved).
* make sure /etc/resolv.conf is a symlink to /run/systemd/resolve/resolv.conf
* restart NetworkManager systemctl restart NetworkManager

**Comment by maulayyacyber** [comment]
I am have same problem. Upgrade from ubuntu 20.04 to 22.04.

**Comment by FaycalBorsali** [comment]
I have the same issue :

My conf now is the following :
- I ran `valet install` (this generates the `/opt/valet-linux/resolv.conf` file and makes `/etc/resolv.conf` point to it)
- I added a file `/opt/valet-linux/custom-nameservers` with the lines `nameserver 8.8.8.8` and `nameserver 8.8.4.4` inspired by old issues of this repo (that I cannot find right now)

The problem :

Every few hours, for an unknown reason (that's where the fix should happen), valet (or some other process ?!) rewrites the file `/opt/valet-linux/resolv.conf` to contain only one line `nameserver 127.0.0.1` (that what causes the loss of Network connection)
My temporary fix is to :

1. re-run `valet install`
2. restart my Network connection (by turning it off then on again from the top right menu)

It works for a few hours before causing the same problem

I am not sure but I think rebooting also causes the same issue.

I hope this helps identify the root of the problem

**Comment by shaband** [comment]
I am have same problem. Upgrade from ubuntu 22.04.

**Comment by cognitus** [comment]
ref #325 @jmarcher maybe you can help

**Comment by yogasukma** [comment]
Another attempt to fix this https://github.com/cpriego/valet-linux/issues/354#issuecomment-1108043017  
  
Not sure, didn't try it yet.

**Comment by sstuppi** [comment]
> Another attempt to fix this [#354 (comment)](https://github.com/cpriego/valet-linux/issues/354#issuecomment-1108043017)
> 
> Not sure, didn't try it yet.

I tried this fix and it works for me.
However, I had another issue. My nginx went down and I coudn't restart the server.
systemctl status nginx.service showed an error:

host not found in "default_server" of the "listen" directive in /etc/nginx/sites-enabled/valet.conf:2

So I edited /etc/nginx/sites-enabled/valet.conf and on line 2 the message appeared:
listen default_server;

I changed it in 
listen 80 default_server;

After reloading nginx everything worked fine!

**Comment by reppair** [comment]
For me, a simple restart of the DHCP client does fix the "no internet" problem, of I got the google dns added to `custom-nameservers` and did add the dnsmasq except loopback interface option.. whatever I do, I can't get valet for linux to serve my projects..

**Comment by liuzhaobo1999** [comment]
另外一个问题就是nginx报错：`host not found in "default_server" of the "listen" directive in /etc/nginx/sites-enabled/valet.conf`
这个也是读不到～/.valet/config.json里面的配置信息port导致的，所以需要重新设置一下端口：`valet port 80`

**Comment by nathan-io** [comment]
I also randomly started Nginx startup failure with _"host not found in "default_server" of the "listen" directive in /etc/nginx/sites-enabled/valet.conf"_ today for the first time on a new-ish WSL2 install. I didn't restart, so I'm not sure what triggered it.

Running `valet port 80` as recommended by @liuzhaobo1999 resolved the issue for me.

**Comment by C4pt4inM** [comment]
I want to add something. may be everyone does not check how "internet was not working" I do by using ping.  when after installation of latest valet, when I did ping google.com . the ip which dns resolved was my local machine ip 127.0.0.1 . 
I tried different approach, but in the end I completely removed composer and reinstall last version ( 2.2.31) . worked perfectly. so there is something with this version.

**Comment by chrisdicarlo** [comment]
> I want to add something. may be everyone does not check how "internet was not working" I do by using `ping`. when after installation of latest valet, when I did `ping google.com` . the ip which dns resolved was my local machine ip `127.0.0.1 `. I tried different approach, but in the end I completely removed composer and reinstall last version ( 2.2.31) . worked perfectly. so there is something with this version.

After struggling with this issue for about an hour I simply downgraded to version 2.2.31 and it just worked!  Thanks for the pointer @C4pt4inM !

**Comment by parkourben99** [comment]
> > I want to add something. may be everyone does not check how "internet was not working" I do by using `ping`. when after installation of latest valet, when I did `ping google.com` . the ip which dns resolved was my local machine ip `127.0.0.1 `. I tried different approach, but in the end I completely removed composer and reinstall last version ( 2.2.31) . worked perfectly. so there is something with this version.
> 
> After struggling with this issue for about an hour I simply downgraded to version 2.2.31 and it just worked! Thanks for the pointer @C4pt4inM !

After fighting with this for hours, this worked for me.

**Comment by Alecaddd** [comment]
@cpriego There seem to be a couple of places in the last release (`2.2.32`) where things are causing issues with the latest Ubuntu 22.04 and PHP 8.

(Most likely unrelated) Little nit with an extra return that will never be reached: https://github.com/cpriego/valet-linux/blob/f1264e29fcd89ec34c40a5eb08cb6ed603d25022/cli/Valet/PhpFpm.php#L246-L248

It seems to be that moving the installation of the configuration after ngxin, phpfpm, and dnsmasq installation is what caused the problem: https://github.com/cpriego/valet-linux/blob/f1264e29fcd89ec34c40a5eb08cb6ed603d25022/cli/valet.php#L40

**Comment by jmarcher** [comment]
I'll take a look when I find some spare time

Alessandro ***@***.***> schrieb am So., 26. Juni 2022, 18:33:

**Comment by Alecaddd** [comment]
Was this closed by accident? I don't see any code changes indicating that this issue was fixed.

**Comment by skino2019** [comment]
This isn't fixed as far as i can see. ass mentioned by @Alecaddd there hasn't been any code changes to stop this from happening, just some work arounds which may or may not work.

Please could this be reopened until there is a merge for the fixes so we can keep up to date.

Kind Regards,
Mike

**Comment by skino2019** [comment]
Any closer to getting this fixed.... i hate using Homestead lol

**Comment by Adesin-fr** [comment]
Do you still issue this with the last update ?

**Comment by codepuncher** [comment]
Yes; after `composer require cpriego/valet-linux && valet install` DNS is broken.
I have to use your steps here to get internet back: https://github.com/cpriego/valet-linux/issues/375#issuecomment-1246295237

**Comment by skino2019** [comment]
> Yes; after `composer require cpriego/valet-linux && valet install` DNS is broken. I have to use your steps here to get internet back: [#375 (comment)](https://github.com/cpriego/valet-linux/issues/375#issuecomment-1246295237) I also have submitted another issue #387

If you are updating from an older version u need to re-sinstall fresh installs should work absolutely fine. I've just tested it on Fedora and Ubuntu with no issues.

**Comment by markovic-nikola** [comment]
> > Yes; after `composer require cpriego/valet-linux && valet install` DNS is broken. I have to use your steps here to get internet back: [#375 (comment)](https://github.com/cpriego/valet-linux/issues/375#issuecomment-1246295237) I also have submitted another issue #387
> 
> If you are updating from an older version u need to re-sinstall fresh installs should work absolutely fine. I've just tested it on Fedora and Ubuntu with no issues.

It seems that @codepuncher has issues with Manjaro, and I can confirm that I'm still having that DNS issue with my Manjaro instance.
