### ISSUE TITLE
Secured domains's certificate not trusted.

### ISSUE THREAD

**Issue by pavinthan** [cpriego/valet-linux#79]
NET::ERR_CERT_AUTHORITY_INVALID
Please check trustCertificate method, please fix as soon as possible.

OS - Ubuntu 17.04 64-bit
Browser - Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by TheNodi** [comment]
Valet generates a [Self-signed Certificate](https://en.wikipedia.org/wiki/Self-signed_certificate) when "securing" a domain. This allows you to test out HTTPS on your local machine during development, valet is NOT a production tool to serve your website to the public.

You are seeing this error because the certificate has not been issued by an authorized certificate authority. On Chrome press "Advanced" and "Proceed to ...." to bypass the error screen. 

You can learn more about HTTPS and how certificates work here:
- https://en.wikipedia.org/wiki/HTTPS
- https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/
- https://en.wikipedia.org/wiki/Self-signed_certificate

**Comment by pavinthan** [comment]
I understood but Valet create certificate authorities for ubuntu 16.04 if the certificate have authority it will trust by machine otherwise it will failed the issue is the same process did not created the authority for the certificate,  currently chrome not allowed invalid certificate for use services such as geolocation and service worker, payment api, if you need this kind of certificate you don't need to create for every domain you can use localhost certificate for the https word. Please care it.

**Comment by TheNodi** [comment]
I apologies for that, I completely forgot we were trying to trust the self-signed certificate. 

The command is still valid looking at the chromium wiki, so it's pretty strange it isn't working.

Have you closed and reopened chrome after securing the site? Is `libnss3-tools` installed? Does it work on firefox?

You can verify if the certificate has been inserted in the database using:
```
certutil -d sql:$HOME/.pki/nssdb -L
```

And you can try to insert it manually (to see if there're errors) using:
```
certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "site_name.dev" -i "/home/your_user/.valet/Certificates/site_name.dev.crt"
```

**Comment by cpriego** [comment]
Fixed in release [v2.0.20](https://github.com/cpriego/valet-linux/releases/tag/v2.0.20)

**Comment by stephan-v** [comment]
This is not fixed, the certificate is properly added in chrome but I am still getting:

`NET::ERR_CERT_AUTHORITY_INVALID`

**Comment by chiptu** [comment]
I had the same problem just go into your browser -> certifcate ->  authorities -> import LaravelValetCASelfSigned 

LaravelValetCASelfSigned is place in your $HOME/.valet/CA

Then if you re on chrome just enable this parameter chrome://flags/#allow-insecure-localhost .

If you re not on chrome you should have a parameter like this to find.

**Comment by sammyaxe** [comment]
I had to run

```certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n "Laravel Valet CA Self Signed CN" -i ~/.valet/CA/LaravelValetCASelfSigned.pem``` to add this to Chrome
